create table if not exists public.automations (
  id bigint generated by default as identity primary key,
  sort_order integer not null,
  draft_slug text not null,
  published_slug text,
  draft_json jsonb not null,
  published_json jsonb,
  archived_at bigint,
  created_at bigint not null,
  updated_at bigint not null,
  published_at bigint,
  created_by text,
  updated_by text,
  published_by text
);

create table if not exists public.automation_slug_redirects (
  id bigint generated by default as identity primary key,
  automation_id bigint not null references public.automations(id) on delete cascade,
  from_slug text not null,
  to_slug text not null,
  created_at bigint not null
);

create unique index if not exists idx_automations_draft_slug
  on public.automations (draft_slug);

create unique index if not exists idx_automations_published_slug
  on public.automations (published_slug)
  where published_slug is not null;

create index if not exists idx_automations_sort_order
  on public.automations (sort_order);

create index if not exists idx_automations_archived_at
  on public.automations (archived_at);

create unique index if not exists idx_automation_redirects_from_slug
  on public.automation_slug_redirects (from_slug);

create index if not exists idx_automation_redirects_automation_id
  on public.automation_slug_redirects (automation_id);

alter table public.automations enable row level security;
alter table public.automation_slug_redirects enable row level security;

-- The app reads and writes catalogue data only from server-side code using the
-- Supabase service-role key. No browser/public table policies are required.
